[build]
  publish = "/"
  functions = "netlify/functions"

[[headers]]
  for = "/src/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"